# Generated by Django 5.0.1 on 2024-01-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='img',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_images', to='tasks.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='task_images', to='tasks.image'),
        ),
    ]
