# Generated by Django 5.0.1 on 2024-01-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='img',
        ),
    ]
